language: r
cache: packages
warnings_are_errors: true

r_packages:
  - crayon
  - rmarkdown
  - cli
  - devtools
  - miniCRAN
  - stringi
  - stringr
  - roxygen2
  - Rcpp
  - R2HTML
  - pander
  - xtable

## test different platforms
jobs:
  include:
  - os: linux
    r: oldrel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB1
  - os: linux
    r: release
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB2
  - os: linux
    r: devel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB3
  - os: osx
    r: release
    env: CACHE_NAME=JOB4

##create notifications
notifications:
  email:
    recipients:
      - sk@r-luminescence.de
    on_success: change
    on_failure: change
